/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookConsultationRouteImport } from './routes/book-consultation'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConsultationsRouteImport } from './routes/admin.consultations'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConsultationRoute = BookConsultationRouteImport.update({
  id: '/book-consultation',
  path: '/book-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultationsRoute = AdminConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-consultation': typeof BookConsultationRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-consultation': typeof BookConsultationRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-consultation': typeof BookConsultationRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book-consultation'
    | '/admin/consultations'
    | '/admin/notifications'
    | '/admin/whatsapp'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-consultation'
    | '/admin/consultations'
    | '/admin/notifications'
    | '/admin/whatsapp'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book-consultation'
    | '/admin/consultations'
    | '/admin/notifications'
    | '/admin/whatsapp'
    | '/admin_/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookConsultationRoute: typeof BookConsultationRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-consultation': {
      id: '/book-consultation'
      path: '/book-consultation'
      fullPath: '/book-consultation'
      preLoaderRoute: typeof BookConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultations': {
      id: '/admin/consultations'
      path: '/consultations'
      fullPath: '/admin/consultations'
      preLoaderRoute: typeof AdminConsultationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminConsultationsRoute: typeof AdminConsultationsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConsultationsRoute: AdminConsultationsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookConsultationRoute: BookConsultationRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
